export const selectors = {
  dropdownList: document.querySelector(".nav__dropdown__list"),
  darkModeSwitch: document.querySelector(".dark__mode__switch"),
  darkModeCircle: document.querySelector(".dark__mode__circle"),
  servicesList: document.querySelector(".services__list"),
  seeMoreServicesBtn: document.querySelector(".services .see__more"),
  seeMoreSuggestedServicesBtn: document.querySelector(
    ".suggested__services .see__more"
  ),
  addOnList: document.querySelector(".add__on__list"),
  sliderPreviousBtn: document.querySelector(".slider__previous__btn"),
  sliderNextBtn: document.querySelector(".slider__next__btn"),
  sliderImagesContainer: document.querySelector(".slider__images"),
  sliderImages: document.querySelectorAll(".slider__images img"),
  sliderDots: document.querySelectorAll(".slider__dots span"),
  selectAllAddOnsBtn: document.querySelector(".add__ons__select__all"),
  increaseQuantityBtn: document.querySelector(".increase__quantity"),
  decreaseQuantityBtn: document.querySelector(".decrease__quantity"),
  quantityNumber: document.querySelector(".purchase__quantity__number"),
  purchasePrice: document.querySelector(".purchase__price"),
  purchaseBtn: document.querySelector(".purchase__btn"),
  reviewersList: document.querySelector(".reviewers__list"),
  suggestedServicesList: document.querySelector(".suggested__services__list"),
  userBtn: document.querySelector(".nav__user__profile"),
  commentInput: document.querySelector(".reviewers__comment__input"),
};
